spring:
  cloud:
    gateway:
      routes:
        - id: json-grpc
          uri: http://0.0.0.0:9393
          predicates:
            - Path=/json/**
          filters:
            - name: JsonToGrpc
              args:
                protoDescriptor: file:proto/descriptors/main.dsc
                protoFile: file:proto/hello.proto
                service: HelloService
                method: sayHello
