spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 340920146854-qsqsr5k3cj9q5rslhiaiq8v4d61i9jo8.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:8080/login
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: name
