logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG

grpc:
  server:
    reflectionServiceEnabled: true
    security:
      enabled: true
      certificateChain: classpath:certificate.pem
      privateKey: classpath:cert.key
    port: 9393
